name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Google Cloud
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform
      run: terraform plan -var="credentials=${{ secrets.GCP_CREDENTIALS }}" -var="project_id=${{ secrets.GCP_PROJECT }}" -var="region=us-central1" -var="zone=us-central1-a" -out=tfplan

    - name: Apply Terraform
      run: terraform apply -var="credentials=${{ secrets.GCP_CREDENTIALS }}" -var="project_id=${{ secrets.GCP_PROJECT }}" -var="region=us-central1" -var="zone=us-central1-a" -auto-approve tfplan
